name: celeba
model: CELEBANet
data_dir: datasets/celeba
num_classes: 6
learning_rate: 0.00001
train_batch_size: 16
test_batch_size: 2
weight_decay: 0.01
min_clients: 500
max_clients: 3000
ditto_lambda: 0.1
eta: 0.1
error_threshold: 0.3
train_samples_file: training_samples_v1.json
