name: cifar10
model: CIFAR10ResNet18
data_dir: datasets/cifar10/alpha_0_2
num_classes: 10
learning_rate: 0.01
train_batch_size: 32
test_batch_size: 8
weight_decay: 0.001
client_fraction: 0.6
ditto_lambda: 0.1
eta: 0.002
error_threshold: 0.4
train_samples_file: training_samples_v1.json
global_rounds: 300
local_rounds: 5
